</usr/share/alsa/alsa.conf>
pcm.wslg_output { type pulse }
ctl.wslg_output { type pulse }
pcm.!default { type pulse }
ctl.!default { type pulse }
pcm.browser { type pulse }
pcm.browser_card { type pulse }
pcm.browser_fullscreen { type pulse }
pcm.chromium_app { type pulse }
pcm.mediaserver { type pulse }
pcm.spotify { type pulse }
pcm.app_out_media { type pulse }
pcm.app_out_media1 { type pulse }
pcm.app_out_media2 { type pulse }
pcm.app_out_media3 { type pulse }
pcm.app_out_media4 { type pulse }
pcm.app_out_chromium { type pulse }
pcm.app_out_announcement { type pulse }
pcm.app_out_user_feedback { type pulse }
pcm.userFeedback { type pulse }
pcm.announcement { type pulse }
pcm.fart { type pulse }
pcm.chime { type pulse }
pcm.media { type pulse }
pcm.navigation { type pulse }
pcm.phone { type pulse }
