</usr/share/alsa/alsa.conf>
pcm.wslg_output { type pulse }
ctl.wslg_output { type pulse }
pcm.!default { type pulse }
ctl.!default { type pulse }
pcm.browser = "wslg_output"
pcm.browser_card = "wslg_output"
pcm.browser_fullscreen = "wslg_output"
pcm.chromium_app = "wslg_output"
pcm.mediaserver = "wslg_output"
pcm.spotify = "wslg_output"
pcm.app_out_media = "wslg_output"
pcm.app_out_media1 = "wslg_output"
pcm.app_out_media2 = "wslg_output"
pcm.app_out_media3 = "wslg_output"
pcm.app_out_media4 = "wslg_output"
pcm.app_out_chromium = "wslg_output"
pcm.app_out_announcement = "wslg_output"
pcm.app_out_user_feedback = "wslg_output"
pcm.userFeedback = "wslg_output"
pcm.announcement = "wslg_output"
