enable_external_compositor=true

[apviz]
ext_comp_view=true

[chromium]
external_composite=true

[gui]
window_manager=true
use_glx=true

[embedded_game_window]
enable_direct_touch_device=false

[ui]
always_swap_buffers=true
always_force_redraw=true
vsync=false
log_all_touch_events=false

[display_state]
wait_for_vehicle_time_ms=0

[bkcam]
forceFeedGood=true
check_deser_state=false
sleep=false
fdselect=false
use_dmabuf_mem_alloc=false
buffers=4
width=1280
height=720
