"""Persistent local QEMU lifecycle, with QMP identity checks before control.

The guest keeps its original kernel and init. TPM state is newly generated by
swtpm; this module supplies no vendor keys, identity material or credentials.
"""
from __future__ import annotations

from contextlib import contextmanager
import json
import os
from pathlib import Path
import shutil
import socket
import subprocess
import time
import uuid

try:
    from .core import atomic_json
    from .qemu_boot import classify_boot
    from .host_graphics import environment as graphics_environment
except ImportError:
    from core import atomic_json
    from qemu_boot import classify_boot
    from host_graphics import environment as graphics_environment


class QMP:
    def __init__(self, path, timeout=3):
        self.socket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self.socket.settimeout(timeout)
        try:
            self.socket.connect(str(path))
            self.stream = self.socket.makefile('rwb', buffering=0)
            if 'QMP' not in self._read():
                raise RuntimeError('The VM control socket did not return a QMP greeting.')
            self.command('qmp_capabilities')
        except Exception:
            self.close()
            raise

    def _read(self):
        line = self.stream.readline(1024 * 1024)
        if not line or len(line) >= 1024 * 1024:
            raise RuntimeError('The VM control channel closed or returned an oversized response.')
        return json.loads(line)

    def command(self, execute, **arguments):
        identifier = uuid.uuid4().hex
        self.stream.write((json.dumps({'execute': execute, 'arguments': arguments, 'id': identifier}) + '\n').encode())
        for _ in range(100):
            result = self._read()
            if result.get('id') != identifier:
                continue
            if 'error' in result:
                raise RuntimeError(result['error'].get('desc', 'QMP command failed.'))
            return result.get('return')
        raise RuntimeError('The VM control channel did not acknowledge the command.')

    def close(self):
        if hasattr(self, 'stream'):
            self.stream.close()
        self.socket.close()

    def __enter__(self):
        return self

    def __exit__(self, *_):
        self.close()


def process_identity(pid):
    """Include Linux start ticks so a recycled process ID cannot match."""
    try:
        proc = Path('/proc') / str(int(pid))
        fields = (proc / 'stat').read_text().rsplit(')', 1)[1].split()
        if fields[0] == 'Z':
            return None
        return {'pid': int(pid), 'start_ticks': int(fields[19]),
                'executable': str((proc / 'exe').resolve(strict=True))}
    except (OSError, ValueError, IndexError):
        return None


def read_state(directory):
    path = Path(directory) / 'vm.json'
    return json.loads(path.read_text()) if path.exists() else {}


@contextmanager
def lifecycle_lock(directory):
    import fcntl
    directory = Path(directory).resolve(strict=True)
    with (directory / 'lifecycle.lock').open('a') as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as exc:
            raise RuntimeError('Another VM lifecycle operation is in progress.') from exc
        yield directory


def verify_identity(directory, state):
    expected = state.get('process')
    if not expected or process_identity(expected['pid']) != expected:
        raise RuntimeError('The recorded VM process is no longer running; no process was controlled.')
    channel = QMP(Path(directory) / 'vm-qmp.sock')
    try:
        if channel.command('query-uuid').get('UUID') != state['uuid']:
            raise RuntimeError('The VM control socket belongs to a different VM.')
        return channel
    except Exception:
        channel.close()
        raise


def tail(path, limit=12000):
    try:
        with Path(path).open('rb') as stream:
            stream.seek(0, os.SEEK_END)
            stream.seek(max(0, stream.tell() - limit))
            return stream.read(limit).decode(errors='replace')
    except FileNotFoundError:
        return ''


def boot_evidence(path):
    """Retain early boot milestones when formatting makes the log tail grow."""
    try:
        with Path(path).open('rb') as stream:
            beginning = stream.read(128 * 1024).decode(errors='replace')
    except FileNotFoundError:
        return ''
    return beginning + '\n' + tail(path)


def status(directory):
    directory = Path(directory)
    state = read_state(directory)
    if not state:
        legacy = directory / 'runtime-qmp.sock'
        if legacy.exists():
            try:
                with QMP(legacy) as channel:
                    actual = channel.command('query-status')
                return {'phase': 'development', 'qemu_status': actual['status'],
                        'desktop_verified': False, 'log_tail': tail(directory / 'runtime-serial.log'),
                        'detail': 'A development VM is active. It has not been adopted by the persistent manager.'}
            except (OSError, RuntimeError, ValueError) as exc:
                return {'phase': 'unreachable', 'desktop_verified': False,
                        'detail': 'The development control socket could not be verified: ' + str(exc)}
        return {'phase': 'stopped', 'desktop_verified': False}
    result = {'uuid': state['uuid'], 'desktop_verified': False,
              'started_at': state['started_at'], 'log_tail': tail(directory / 'vm-serial.log')}
    expected = state.get('process')
    if not expected or process_identity(expected['pid']) != expected:
        result.update(phase='stopped', detail='The recorded VM process has exited.')
        return result
    try:
        with verify_identity(directory, state) as channel:
            actual = channel.command('query-status')
        result.update(phase='booting' if actual.get('running') else actual['status'],
                      qemu_status=actual['status'], process=expected)
    except (OSError, RuntimeError, ValueError) as exc:
        # A live process with an unavailable socket is not proof of shutdown.
        result.update(phase='unreachable', detail=str(exc), process=expected)
    result['boot'] = classify_boot(boot_evidence(directory / 'vm-serial.log'), observing=True)
    if state.get('shutdown_requested_at'):
        result['shutdown_requested_at'] = state['shutdown_requested_at']
    return result


def option_path(path):
    return str(path).replace(',', ',,')


def launch_arguments(directory, identity, *, graphics=True, internet=False, tpm=True,
                     executable='qemu-system-x86_64'):
    directory = Path(directory)
    args = [str(executable), '-name', 'Infotainment Lab | Firmware VM',
            '-uuid', identity, '-machine', 'q35,accel=kvm', '-cpu', 'host', '-smp', '4',
            '-m', '2048', '-nodefaults', '-display', 'gtk,gl=off' if graphics else 'none',
            '-device', 'VGA', '-monitor', 'none',
            '-serial', 'file:' + str(directory / 'vm-serial.log'),
            '-qmp', 'unix:' + option_path(directory / 'vm-qmp.sock') + ',server=on,wait=off',
            '-no-reboot', '-kernel', str(directory / 'vendor-kernel'),
            '-append', 'console=ttyS0,115200 earlyprintk=serial bootpart=kernel-a ro panic=0 security=apparmor apparmor=1',
            '-device', 'sdhci-pci',
            '-drive', 'if=none,id=sdcard,file=' + option_path(directory / 'guest-runtime.qcow2') + ',format=qcow2',
            '-device', 'sd-card,drive=sdcard',
            # Firmware stage 1 assigns eth0=192.168.90.100 and reserves it for
            # the local vehicle segment; ConnMan deliberately ignores eth0.
            '-nic', 'user,model=igb,net=192.168.90.0/24,host=192.168.90.1,dns=192.168.90.2,restrict=on']
    if internet:
        # The optional second NIC is a separate upstream candidate. Its
        # presence alone is not proof of a configured guest route or DNS.
        args += ['-nic', 'user,model=igb']
    if tpm:
        args += ['-chardev', 'socket,id=tpm,path=' + option_path(directory / 'tpm.sock'),
                 '-tpmdev', 'emulator,id=tpm0,chardev=tpm', '-device', 'tpm-tis,tpmdev=tpm0']
    return args


def start(directory, *, graphics=True, internet=False, executable='qemu-system-x86_64'):
    with lifecycle_lock(directory) as directory:
        ensure_idle(directory)
        return _start_idle(directory, graphics=graphics, internet=internet, executable=executable)


def ensure_idle(directory):
    """Call under lifecycle_lock before touching a guest kernel or backing disk."""
    directory = Path(directory)
    old = read_state(directory)
    for key in ('process', 'tpm_process'):
        expected = old.get(key)
        if expected and process_identity(expected['pid']) == expected:
            raise RuntimeError('This VM or its virtual TPM is still running; its files have been left unchanged.')
    for name in ('vm-qmp.sock', 'runtime-qmp.sock'):
        control = directory / name
        if not control.exists():
            continue
        try:
            with QMP(control) as channel:
                channel.command('query-status')
        except (ConnectionRefusedError, FileNotFoundError):
            if name == 'runtime-qmp.sock':
                pidfile = directory / 'runtime.pid'
                try:
                    pid = int(pidfile.read_text())
                except (OSError, ValueError) as exc:
                    raise RuntimeError('The development VM process could not be verified; its files have been left unchanged.') from exc
                if process_identity(pid):
                    raise RuntimeError('The development VM process is still present; its files have been left unchanged.')
        except (OSError, RuntimeError, ValueError) as exc:
            raise RuntimeError('The existing VM control socket could not be verified; its files have been left unchanged.') from exc
        else:
            raise RuntimeError('An active VM already owns this control socket; its files have been left unchanged.')


def _start_idle(directory, *, graphics, internet, executable):
    # The caller holds lifecycle_lock through preparation and QMP registration.
    for name in ('qemu-system-x86_64', 'qemu-img', 'swtpm'):
        if not shutil.which(name):
            raise RuntimeError(f'Install {name} in this Linux distribution before starting the VM.')
    emulator = shutil.which(str(executable))
    if not emulator:
        raise RuntimeError('The selected QEMU executable is unavailable.')
    if not os.access('/dev/kvm', os.R_OK | os.W_OK):
        raise RuntimeError('The current Linux user cannot access KVM.')
    if graphics and not (os.environ.get('DISPLAY') or os.environ.get('WAYLAND_DISPLAY')):
        raise RuntimeError('A Linux desktop or WSLg display is required for the VM window.')
    manifest = json.loads((directory / 'storage.json').read_text())
    if not manifest.get('volume_group_provisioned'):
        raise RuntimeError('Prepare the guest volume group before starting this VM.')
    base = directory / 'guest-storage.raw'
    if base.is_symlink() or not base.is_file() or base.stat().st_size != manifest['disk_bytes']:
        raise RuntimeError('The guest base disk does not match its storage manifest.')
    if not (directory / 'vendor-kernel').is_file():
        raise RuntimeError('The extracted vendor kernel is missing.')
    overlay = directory / 'guest-runtime.qcow2'
    if not overlay.exists():
        subprocess.run(['qemu-img', 'create', '-f', 'qcow2', '-F', 'raw', '-b', str(base), str(overlay)],
                       check=True, capture_output=True, timeout=30)
    info = json.loads(subprocess.run(['qemu-img', 'info', '--output=json', str(overlay)],
                     check=True, capture_output=True, text=True, timeout=10).stdout)
    if overlay.is_symlink() or info['format'] != 'qcow2' or Path(info.get('full-backing-filename', '')).resolve() != base:
        raise RuntimeError('The VM overlay does not reference this prepared base disk.')
    tpm_dir = directory / 'tpm-state'
    tpm_dir.mkdir(mode=0o700, exist_ok=True)
    identifier = str(uuid.uuid4())
    tpm_process = guest = None
    with (directory / 'vm-launch.log').open('ab') as log:
        try:
            tpm_process = subprocess.Popen(['swtpm', 'socket', '--tpm2', '--terminate',
                '--tpmstate', 'dir=' + option_path(tpm_dir), '--ctrl',
                'type=unixio,path=' + option_path(directory / 'tpm.sock') + ',mode=0600'],
                stdin=subprocess.DEVNULL, stdout=log, stderr=log, start_new_session=True)
            for _ in range(50):
                if tpm_process.poll() is not None:
                    raise RuntimeError('The virtual TPM stopped during startup; inspect vm-launch.log.')
                if (directory / 'tpm.sock').exists(): break
                time.sleep(.1)
            else:
                raise RuntimeError('The virtual TPM control socket did not become ready.')
            guest = subprocess.Popen(launch_arguments(directory, identifier, graphics=graphics,
                internet=internet, executable=emulator),
                stdin=subprocess.DEVNULL, stdout=log, stderr=log, start_new_session=True,
                env=graphics_environment() if graphics else None)
            state = {'uuid': identifier, 'process': process_identity(guest.pid),
                     'tpm_process': process_identity(tpm_process.pid), 'started_at': time.time(),
                     'graphics': graphics, 'internet': internet, 'tpm': 'swtpm2',
                     'emulator': emulator}
            for _ in range(100):
                if guest.poll() is not None:
                    raise RuntimeError('QEMU stopped during startup; inspect vm-launch.log.')
                try:
                    with verify_identity(directory, state): pass
                    break
                except (OSError, RuntimeError):
                    time.sleep(.1)
            else:
                raise RuntimeError('QEMU did not expose its verified control channel in time.')
            atomic_json(directory / 'vm.json', state)
        except Exception:
            for child in (guest, tpm_process):
                if child and child.poll() is None:
                    child.terminate()
                    try: child.wait(timeout=5)
                    except subprocess.TimeoutExpired:
                        child.kill()
                        child.wait(timeout=5)
            raise
    return status(directory)


def shutdown(directory):
    """Request guest ACPI shutdown; never silently escalate to power removal."""
    with lifecycle_lock(directory) as directory:
        state = read_state(directory)
        with verify_identity(directory, state) as channel:
            channel.command('system_powerdown')
        state['shutdown_requested_at'] = time.time()
        atomic_json(directory / 'vm.json', state)
        return status(directory)
