"""Device library and live session layout for the native emulator-style shell."""
import os
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QLineEdit, QListWidget,
                              QCheckBox, QComboBox, QGroupBox)
from .material_widgets import MaterialSwitch as QCheckBox
from .presentation import DisplayOverview, icon


def build_workspace(window, label, card, DropArea):
    page = QWidget()
    layout = QVBoxLayout(page)
    layout.setContentsMargins(0, 8, 0, 0)
    layout.setSpacing(10)

    window.steps = label('', 'muted', True)
    layout.addWidget(window.steps)
    columns = QHBoxLayout()
    columns.setSpacing(18)
    library, left = card()
    window.library_card = library
    library.setFixedWidth(266)
    left.setContentsMargins(18, 20, 18, 20)
    left.setSpacing(12)
    row = QHBoxLayout()
    row.addWidget(label('Your devices', 'subtitle'))
    row.addStretch()
    add = window.button('+', window.choose_files)
    add.setFixedSize(40, 40)
    add.setAccessibleName('Add firmware')
    add.setStyleSheet('padding: 0;')
    add.setIcon(icon('add'))
    add.setText('')
    add.setToolTip('Add firmware · Ctrl+O')
    row.addWidget(add)
    left.addLayout(row)
    window.search = QLineEdit()
    window.search.setPlaceholderText('Find a device…')
    window.search.setClearButtonEnabled(True)
    window.search.textChanged.connect(window.filter_library)
    left.addWidget(window.search)
    window.items = QListWidget()
    window.items.setSpacing(4)
    window.items.setWordWrap(True)
    window.items.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    window.items.setMinimumHeight(100)
    window.items.currentRowChanged.connect(window.device_selected)
    left.addWidget(window.items, 1)
    window.item_detail = label('', 'muted', True)
    left.addWidget(window.item_detail)
    left.addSpacing(6)
    left.addWidget(label('COMPUTER SETUP', 'eyebrow'))
    window.setup_hint = label('', 'muted', True)
    left.addWidget(window.setup_hint)
    window.setup_button = window.button('Prepare computer', window.setup_dependencies)
    left.addWidget(window.setup_button)
    columns.addWidget(library)

    device, right = card()
    right.setContentsMargins(22, 20, 22, 20)
    right.setSpacing(10)
    heading = QHBoxLayout()
    texts = QVBoxLayout()
    window.device_title = label('', 'subtitle')
    window.device_subtitle = label('', 'muted', True)
    texts.addWidget(window.device_title)
    texts.addWidget(window.device_subtitle)
    heading.addLayout(texts, 1)
    window.phase_badge = label('', 'badge')
    heading.addWidget(window.phase_badge)
    right.addLayout(heading)
    window.overview = DisplayOverview()
    window.overview.setMinimumHeight(180)
    window.overview.message = 'Your displays will appear here'
    right.addWidget(window.overview, 1)
    window.preview_caption = label('Display overview · Open a screen to interact', 'muted')
    right.addWidget(window.preview_caption)
    status_row = QHBoxLayout()
    window.metrics = {}
    for key, en in (('center', 'Center'), ('instruments', 'Instruments'), ('chromium', 'Chromium')):
        value = label(en + ' · —', 'muted')
        status_row.addWidget(value)
        window.metrics[key] = value
    right.addLayout(status_row)
    window.renderer_label = label('', 'muted', True)
    right.addWidget(window.renderer_label)

    options = QGroupBox('Launch options')
    opt = QVBoxLayout(options)
    window.engine_box = QComboBox()
    window.engine_box.addItem('Native Linux / WSL', 'native')
    window.engine_box.addItem('QEMU virtual machine', 'qemu')
    window.engine_box.setCurrentIndex(window.engine_box.findData(window.bridge.engine))
    window.engine_box.setAccessibleName('Execution mode')
    window.engine_box.currentIndexChanged.connect(window.change_engine)
    opt.addWidget(window.engine_box)
    window.vm_options = QWidget()
    vm_row = QHBoxLayout(window.vm_options)
    vm_row.setContentsMargins(0, 0, 0, 0)
    window.vm_directory = QLineEdit(window.bridge.vm_directory)
    window.vm_directory.setPlaceholderText('Guest directory · default application storage')
    window.vm_directory.setAccessibleName('QEMU guest directory')
    window.vm_directory.editingFinished.connect(window.change_vm_directory)
    vm_row.addWidget(window.vm_directory, 1)
    window.vm_browse = window.button('Browse…', window.choose_vm_directory)
    vm_row.addWidget(window.vm_browse)
    window.vm_options.setVisible(window.bridge.engine == 'qemu')
    opt.addWidget(window.vm_options)
    row = QHBoxLayout()
    window.cluster_box = QCheckBox('Instrument display')
    window.browser_box = QCheckBox('Embedded Chromium')
    window.cluster_box.setChecked(True)
    window.browser_box.setChecked(True)
    row.addWidget(window.cluster_box)
    row.addWidget(window.browser_box)
    opt.addLayout(row)
    window.advanced = window.button('More options  ▾', lambda: window.advanced_panel.setVisible(not window.advanced_panel.isVisible()))
    opt.addWidget(window.advanced)
    window.advanced_panel = QWidget()
    more = QVBoxLayout(window.advanced_panel)
    more.setContentsMargins(0, 0, 0, 0)
    window.maps_box = QComboBox()
    more.addWidget(window.maps_box)
    more.addWidget(label('Maps: mount only; navigation is not connected yet.', 'muted', True))
    window.distro_box = QComboBox()
    window.distro_box.setEditable(True)
    window.distro_box.addItems(['Debian', 'Ubuntu'])
    window.distro_box.setCurrentText(window.bridge.distro)
    window.distro_box.setVisible(os.name == 'nt')
    window.distro_box.currentTextChanged.connect(window.change_distro)
    more.addWidget(window.distro_box)
    window.advanced_panel.hide()
    opt.addWidget(window.advanced_panel)
    right.addWidget(options)
    for box in (window.cluster_box, window.browser_box):
        box.toggled.connect(window.save_options)
    window.maps_box.currentIndexChanged.connect(window.save_options)
    actions = QHBoxLayout()
    window.start_button = window.button('Start device', window.start_session, True)
    window.start_button.setIcon(icon('play'))
    window.stop_button = window.button('Stop', lambda: window.operation('stop'))
    window.stop_button.setObjectName('danger')
    actions.addWidget(window.start_button, 2)
    actions.addWidget(window.stop_button, 1)
    right.addLayout(actions)
    window.qemu_button = window.button('QEMU boot check', window.check_qemu)
    window.reset_button = window.button('Full reset', window.full_reset)
    window.reset_button.setToolTip('Stop the session and delete cached data, saved settings and the library index')
    tools = QHBoxLayout()
    tools.addWidget(window.qemu_button, 2)
    tools.addWidget(window.reset_button, 1)
    right.addLayout(tools)
    columns.addWidget(device, 1)
    layout.addLayout(columns, 1)
    drop = DropArea('Drop firmware to add a device',
                    'Or click to choose a local .mcu2, .ice or SquashFS file.')
    drop.files.connect(window.queue_imports)
    drop.clicked.connect(window.choose_files)
    layout.addWidget(drop)
    return page
