"""Device library and live session layout for the native emulator-style shell."""
import os
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QLineEdit, QListWidget,
                              QCheckBox, QComboBox, QGroupBox)
from .presentation import DisplayOverview, icon


def build_workspace(window, label, card, DropArea):
    tr = window.tr2
    page = QWidget()
    layout = QVBoxLayout(page)
    layout.setContentsMargins(0, 8, 0, 0)
    layout.setSpacing(10)

    window.steps = label('', 'muted', True)
    layout.addWidget(window.steps)
    columns = QHBoxLayout()
    columns.setSpacing(18)
    library, left = card()
    library.setFixedWidth(266)
    left.setContentsMargins(18, 20, 18, 20)
    left.setSpacing(12)
    row = QHBoxLayout()
    row.addWidget(label(tr('Your devices', '我的设备'), 'subtitle'))
    row.addStretch()
    add = window.button('+', '+', window.choose_files)
    add.setFixedSize(38, 32)
    add.setAccessibleName(tr('Add firmware', '添加固件'))
    add.setStyleSheet('padding: 0;')
    add.setIcon(icon('add'))
    add.setText('')
    add.setToolTip(tr('Add firmware · Ctrl+O', '添加固件 · Ctrl+O'))
    row.addWidget(add)
    left.addLayout(row)
    window.search = QLineEdit()
    window.search.setPlaceholderText(tr('Find a device…', '搜索设备…'))
    window.search.setClearButtonEnabled(True)
    window.search.textChanged.connect(window.filter_library)
    left.addWidget(window.search)
    window.items = QListWidget()
    window.items.setSpacing(4)
    window.items.setMinimumHeight(100)
    window.items.currentRowChanged.connect(window.device_selected)
    left.addWidget(window.items, 1)
    window.item_detail = label('', 'muted', True)
    left.addWidget(window.item_detail)
    left.addSpacing(6)
    left.addWidget(label(tr('COMPUTER SETUP', '电脑环境'), 'eyebrow'))
    window.setup_hint = label('', 'muted', True)
    left.addWidget(window.setup_hint)
    window.setup_button = window.button('Prepare computer', '准备运行环境', window.setup_dependencies)
    left.addWidget(window.setup_button)
    columns.addWidget(library)

    device, right = card()
    right.setContentsMargins(22, 20, 22, 20)
    right.setSpacing(10)
    heading = QHBoxLayout()
    texts = QVBoxLayout()
    window.device_title = label('', 'subtitle')
    window.device_subtitle = label('', 'muted', True)
    texts.addWidget(window.device_title)
    texts.addWidget(window.device_subtitle)
    heading.addLayout(texts, 1)
    window.phase_badge = label('', 'badge')
    heading.addWidget(window.phase_badge)
    right.addLayout(heading)
    window.overview = DisplayOverview()
    window.overview.message = tr('Your displays will appear here', '启动后显示屏幕预览')
    right.addWidget(window.overview, 1)
    window.preview_caption = label(tr('Display overview · Open a screen to interact', '屏幕预览 · 打开显示窗口即可操作'), 'muted')
    right.addWidget(window.preview_caption)
    status_row = QHBoxLayout()
    window.metrics = {}
    for key, en, zh in (('center', 'Center', '中控'), ('instruments', 'Instruments', '仪表'), ('chromium', 'Chromium', '浏览器')):
        value = label(tr(en, zh) + ' · —', 'muted')
        status_row.addWidget(value)
        window.metrics[key] = value
    right.addLayout(status_row)
    window.renderer_label = label('', 'muted', True)
    right.addWidget(window.renderer_label)

    options = QGroupBox(tr('Launch options', '启动选项'))
    opt = QVBoxLayout(options)
    row = QHBoxLayout()
    window.cluster_box = QCheckBox(tr('Instrument display', '仪表窗口'))
    window.browser_box = QCheckBox(tr('Embedded Chromium', '内嵌 Chromium'))
    window.cluster_box.setChecked(True)
    window.browser_box.setChecked(True)
    row.addWidget(window.cluster_box)
    row.addWidget(window.browser_box)
    opt.addLayout(row)
    window.advanced = window.button('More options  ▾', '更多选项  ▾', lambda: window.advanced_panel.setVisible(not window.advanced_panel.isVisible()))
    opt.addWidget(window.advanced)
    window.advanced_panel = QWidget()
    more = QVBoxLayout(window.advanced_panel)
    more.setContentsMargins(0, 0, 0, 0)
    window.maps_box = QComboBox()
    more.addWidget(window.maps_box)
    more.addWidget(label(tr('Maps: mount only; navigation is not connected yet.', '地图目前仅支持挂载，尚未接通导航。'), 'muted', True))
    window.distro_box = QComboBox()
    window.distro_box.setEditable(True)
    window.distro_box.addItems(['Debian', 'Ubuntu'])
    window.distro_box.setCurrentText(window.bridge.distro)
    window.distro_box.setVisible(os.name == 'nt')
    window.distro_box.currentTextChanged.connect(window.change_distro)
    more.addWidget(window.distro_box)
    window.advanced_panel.hide()
    opt.addWidget(window.advanced_panel)
    right.addWidget(options)
    for box in (window.cluster_box, window.browser_box):
        box.toggled.connect(window.save_options)
    window.maps_box.currentIndexChanged.connect(window.save_options)
    actions = QHBoxLayout()
    window.start_button = window.button('Start device', '启动设备', window.start_session, True)
    window.start_button.setIcon(icon('play', '#12392f'))
    window.stop_button = window.button('Stop', '停止', lambda: window.operation('stop'))
    window.stop_button.setObjectName('danger')
    actions.addWidget(window.start_button, 2)
    actions.addWidget(window.stop_button, 1)
    right.addLayout(actions)
    columns.addWidget(device, 1)
    layout.addLayout(columns, 1)
    drop = DropArea(tr('Drop firmware to add a device', '拖入固件，添加设备'),
                    tr('Or click to choose a local .mcu2, .ice or SquashFS file.', '也可点击选择本地 .mcu2、.ice 或 SquashFS 文件。'))
    drop.files.connect(window.queue_imports)
    drop.clicked.connect(window.choose_files)
    layout.addWidget(drop)
    return page
